import Pkg

const _ENV_DIR = joinpath(@__DIR__, "julia_arpack_env")
Pkg.activate(_ENV_DIR; io=devnull)

const _REQ_PKGS = [
    "CSV",
    "DataFrames",
    "KrylovKit",
    "Plots",
]

function ensure_env_ready()
    for p in _REQ_PKGS
        if Base.find_package(p) === nothing
            Pkg.add(p; io=devnull)
        end
    end

    try
        Pkg.instantiate(; io=devnull)
        Pkg.precompile(; io=devnull)
    catch err
        msg = sprint(showerror, err)
        if occursin("Could not locate the source code", msg) || occursin("manifest generated by a different version of Julia", msg)
            manifest_path = joinpath(_ENV_DIR, "Manifest.toml")
            if isfile(manifest_path)
                rm(manifest_path; force=true)
            end
            Pkg.resolve(; io=devnull)
            Pkg.instantiate(; io=devnull)
            Pkg.precompile(; io=devnull)
        else
            rethrow(err)
        end
    end
end

ensure_env_ready()

using SparseArrays, LinearAlgebra
using Random
using CSV, DataFrames
using KrylovKit
using Plots
using Printf

const REQUESTED_EIGENVALUES = 20
const TARGET_SHIFT = 1e-3 + 0.0im
const SOLVER_TOL = 1e-16
const RANDOM_SEED = 0
const LM_PLOT_FILE = "krylovkit_lm.png"

function load_sparse_csv(path::AbstractString)::SparseMatrixCSC{Float64,Int}
    df = CSV.read(path, DataFrame; header=false, types=String)
    vals = Matrix(df)

    toint(x) = x isa Real ? Int(round(Float64(x))) : parse(Int, strip(String(x)))
    tofloat(x) = x isa Real ? Float64(x) : parse(Float64, strip(String(x)))

    nrows = toint(vals[1, 2])
    ncols = toint(vals[1, 3])

    I = map(toint, vals[2:end, 1])
    J = map(toint, vals[2:end, 2])
    V = map(tofloat, vals[2:end, 3])

    return sparse(I, J, V, nrows, ncols)
end

function rel_residual(A, B, λ, x)
    xn = norm(x)
    x = xn > 0 ? x / xn : x
    Ax = A * x
    Bx = B * x
    num = norm(Ax - λ * Bx)
    den = max(norm(Ax), abs(λ) * norm(Bx), 1.0)
    return num / den
end

function parse_shift_arg(s)::ComplexF64
    t = strip(String(s))

    try
        return ComplexF64(parse(ComplexF64, t))
    catch
    end

    try
        return ComplexF64(parse(Float64, t), 0.0)
    catch
    end

    t2 = replace(lowercase(t), " " => "")
    if endswith(t2, "im")
        c = t2[1:end-2]
        imag_val = if c == "" || c == "+"
            1.0
        elseif c == "-"
            -1.0
        else
            parse(Float64, c)
        end
        return ComplexF64(0.0, imag_val)
    end

    error("Could not parse shift '$s'. Examples: 0.001, 10im, 0+10im, -2.5+3im")
end

function sort_by_largest_real(λ::Vector{ComplexF64}, X::Matrix{ComplexF64})
    p = sortperm(real.(λ); rev=true)
    return λ[p], X[:, p]
end

function run_lm_krylov(A::SparseMatrixCSC{ComplexF64,Int}, B::SparseMatrixCSC{ComplexF64,Int}; nev::Int, sigma::ComplexF64, tol::Float64, seed::Int, compute_residuals::Bool=true)
    n = size(A, 1)
    F = lu(A - sigma * B)

    op_count = Ref(0)
    op(v) = begin
        op_count[] += 1
        return F \ (B * v)
    end

    rng = MersenneTwister(seed)
    x0 = ComplexF64.(randn(rng, n))

    nev_eff = min(max(2, nev), n - 2)
    krylovdim = min(n - 1, max(2 * nev_eff + 20, 60))

    t_solve = time()
    μ, vecs, info = KrylovKit.eigsolve(
        op,
        x0,
        nev_eff,
        :LM;
        tol=tol,
        maxiter=5000,
        krylovdim=krylovdim,
    )
    solve_time = time() - t_solve

    μ = ComplexF64.(μ)
    λ = sigma .+ 1.0 ./ μ
    X = hcat([ComplexF64.(v) for v in vecs]...)

    λ, X = sort_by_largest_real(λ, X)
    rr = compute_residuals ? [rel_residual(A, B, λ[i], X[:, i]) for i in eachindex(λ)] : Float64[]

    return λ, X, rr, info, op_count[], solve_time
end

function main()
    benchmark_lm_only = false
    cli_positional = String[]
    for a in ARGS
        if a == "--benchmark-lm-only"
            benchmark_lm_only = true
        else
            push!(cli_positional, a)
        end
    end

    println("Loading K.csv and M.csv ...")
    K = load_sparse_csv("K.csv")
    M = load_sparse_csv("M.csv")

    A = ComplexF64.(-K)
    B = ComplexF64.(M)

    nev = length(cli_positional) >= 1 ? max(1, parse(Int, cli_positional[1])) : REQUESTED_EIGENVALUES
    sigma = length(cli_positional) >= 2 ? parse_shift_arg(cli_positional[2]) : ComplexF64(TARGET_SHIFT)

    t0 = time()
    λ, X, rr, info, nops, solve_time = run_lm_krylov(A, B; nev=nev, sigma=sigma, tol=SOLVER_TOL, seed=RANDOM_SEED, compute_residuals=!benchmark_lm_only)
    elapsed = time() - t0

    if benchmark_lm_only
        println("LM_EIGENSOLVE_COST_S=", @sprintf("%.9f", solve_time))
        println("LM_BENCHMARK_TOTAL_S=", @sprintf("%.9f", elapsed))
        println("LM_META converged=", info.converged, " numiter=", info.numiter, " op_calls=", nops)
        println("completed")
        return
    end

    println("----------------------------------------------------------------------")
    println(" Solver : KRYLOVKIT-LM   elapsed=", round(elapsed, digits=3), " s   count=", length(λ), "  sigma=", sigma)
    println(" Residuals : min=", @sprintf("%.2e", minimum(rr)), "  max=", @sprintf("%.2e", maximum(rr)))
    println(@sprintf(" %3s  %12s  %14s   %s", "#", "Re(lam)", "Im(lam)", "res"))
    for i in eachindex(λ)
        println(@sprintf(" %3d  %+12.6f  %+14.6fj  %.2e", i, real(λ[i]), imag(λ[i]), rr[i]))
    end

    p = scatter(real.(λ), imag.(λ), marker_z=real.(λ), ms=6, alpha=0.85,
                xlabel="Real(λ)", ylabel="Imag(λ)",
                title="Julia KrylovKit LM (shift-invert)",
                legend=false, colorbar_title="Real(λ)", grid=true)
    vline!(p, [0.0], color=:black, lw=1)
    hline!(p, [0.0], color=:black, lw=1)
    savefig(p, LM_PLOT_FILE)
    println("Saved: ", LM_PLOT_FILE)
    println("KrylovKit info: converged=", info.converged, "  numiter=", info.numiter)
    println("Operator applications (op calls): ", nops, "  LU factorizations: 1")
    println("completed")
end

main()
