import Pkg

const _ENV_DIR = joinpath(@__DIR__, "julia_arpack_env")
Pkg.activate(_ENV_DIR; io=devnull)

const _REQ_PKGS = [
    "CSV",
    "DataFrames",
    "Arpack",
    "LinearMaps",
    "Plots",
]

function ensure_env_ready()
    for p in _REQ_PKGS
        if Base.find_package(p) === nothing
            Pkg.add(p; io=devnull)
        end
    end

    try
        Pkg.instantiate(; io=devnull)
        Pkg.precompile(; io=devnull)
    catch err
        msg = sprint(showerror, err)
        if occursin("Could not locate the source code", msg) || occursin("manifest generated by a different version of Julia", msg)
            manifest_path = joinpath(_ENV_DIR, "Manifest.toml")
            if isfile(manifest_path)
                rm(manifest_path; force=true)
            end
            Pkg.resolve(; io=devnull)
            Pkg.instantiate(; io=devnull)
            Pkg.precompile(; io=devnull)
        else
            rethrow(err)
        end
    end
end

ensure_env_ready()

using SparseArrays, LinearAlgebra, Statistics
using Random
using CSV, DataFrames
using Arpack
using LinearMaps
using Plots
using Printf

# ------------------ user inputs (edit these) ------------------
const REQUESTED_EIGENVALUES = 20
const TARGET_SHIFT = 1e-3 + 0.0im
const SOLVER_TOL = 1e-16
const RANDOM_SEED = 0
const CANDIDATE_DEDUP_TOL = 1e-2
const CANDIDATE_DEDUP_ABS = 1e-16
const ZR_NUM_EIG_RUNS = 3
const ZR_IMAG_SHIFT_MIN = 0.0
const ZR_IMAG_SHIFT_MAX = 20.0
const ZR_EIGS_PER_RUN = 10
const LM_PLOT_FILE = "arpack_lm.png"
const ZR_PLOT_FILE = "arpack_zr.png"
 

function load_sparse_csv(path::AbstractString)::SparseMatrixCSC{Float64,Int}
    df = CSV.read(path, DataFrame; header=false, types=String)
    vals = Matrix(df)

    toint(x) = x isa Real ? Int(round(Float64(x))) : parse(Int, strip(String(x)))
    tofloat(x) = x isa Real ? Float64(x) : parse(Float64, strip(String(x)))

    nrows = toint(vals[1, 2])
    ncols = toint(vals[1, 3])

    I = map(toint, vals[2:end, 1])
    J = map(toint, vals[2:end, 2])
    V = map(tofloat, vals[2:end, 3])

    return sparse(I, J, V, nrows, ncols)
end

function rel_residual(A, B, λ, x)
    xn = norm(x)
    x = xn > 0 ? x / xn : x
    Ax = A * x
    Bx = B * x
    num = norm(Ax - λ * Bx)
    den = max(norm(Ax), abs(λ) * norm(Bx), 1.0)
    return num / den
end

function is_better_candidate(new_λ::ComplexF64, new_rr::Float64, old_λ::ComplexF64, old_rr::Float64)
    if new_rr < old_rr * (1 - 1e-12)
        return true
    elseif old_rr < new_rr * (1 - 1e-12)
        return false
    end
    if real(new_λ) > real(old_λ) + 1e-12
        return true
    elseif real(old_λ) > real(new_λ) + 1e-12
        return false
    end
    return abs(new_λ) < abs(old_λ)
end

function unique_push!(vals::Vector{ComplexF64}, vecs::Vector{Vector{ComplexF64}}, ress::Vector{Float64}, λ, x, rr; tol=CANDIDATE_DEDUP_TOL)
    λc = ComplexF64(λ)
    xc = ComplexF64.(x)
    for i in eachindex(vals)
        old = vals[i]
        if abs(λc - old) <= tol * max(1.0, abs(old))
            if is_better_candidate(λc, rr, vals[i], ress[i])
                vals[i] = λc
                vecs[i] = xc
                ress[i] = rr
            end
            return false
        end
    end
    push!(vals, λc)
    push!(vecs, xc)
    push!(ress, rr)
    return true
end

function sort_by_largest_real(λ::Vector{ComplexF64}, X::Matrix{ComplexF64})
    p = sortperm(real.(λ); rev=true)
    return λ[p], X[:, p]
end

function sort_by_smallest_abs_real(λ::Vector{ComplexF64}, X::Matrix{ComplexF64}, rr::Vector{Float64})
    p = sortperm(collect(eachindex(λ)); by=i -> (abs(real(λ[i])), rr[i], abs(imag(λ[i]))))
    return λ[p], X[:, p], rr[p]
end

same_eig(l1::ComplexF64, l2::ComplexF64; rel::Float64=CANDIDATE_DEDUP_TOL, abs_tol::Float64=CANDIDATE_DEDUP_ABS) =
    abs(l1 - l2) <= max(abs_tol, rel * max(1.0, abs(l1), abs(l2)))

function dedup_pool(pool::Vector{Tuple{ComplexF64,Vector{ComplexF64},Float64}}; rel::Float64=CANDIDATE_DEDUP_TOL, abs_tol::Float64=CANDIDATE_DEDUP_ABS)
    kept = Tuple{ComplexF64,Vector{ComplexF64},Float64}[]
    for (λ, x, rr) in pool
        merged = false
        for i in eachindex(kept)
            λ0, x0, rr0 = kept[i]
            if same_eig(λ, λ0; rel=rel, abs_tol=abs_tol)
                if is_better_candidate(λ, rr, λ0, rr0)
                    kept[i] = (λ, x, rr)
                end
                merged = true
                break
            end
        end
        if !merged
            push!(kept, (λ, x, rr))
        end
    end
    return kept
end

function parse_shift_arg(s)::ComplexF64
    t = strip(String(s))

    # Try native complex parser first (e.g., "1+2im", "3-4im")
    try
        return ComplexF64(parse(ComplexF64, t))
    catch
    end

    # Real scalar fallback
    try
        return ComplexF64(parse(Float64, t), 0.0)
    catch
    end

    # Pure imaginary fallback (e.g., "10im", "-2.5im", "im", "-im")
    t2 = replace(lowercase(t), " " => "")
    if endswith(t2, "im")
        c = t2[1:end-2]
        imag_val = if c == "" || c == "+"
            1.0
        elseif c == "-"
            -1.0
        else
            parse(Float64, c)
        end
        return ComplexF64(0.0, imag_val)
    end

    error("Could not parse shift '$s'. Examples: 0.001, 10im, 0+10im, -2.5+3im")
end

function run_shift(A::SparseMatrixCSC{ComplexF64,Int}, B::SparseMatrixCSC{ComplexF64,Int}; nev::Int, sigma, tol=1e-10, maxiter=1500, ncv::Int=max(nev + 30, 120), v0=nothing)
    n = size(A, 1)
    S = A - sigma * B

    F = lu(S)
    T = LinearMap{ComplexF64}(n, n; ismutating=false) do x
        F \ (B * x)
    end

    local_v0 = v0 === nothing ? nothing : ComplexF64.(v0)

    t_solve = time()
    μ, X, nconv, niter, nmult, resid = Arpack.eigs(
        T;
        nev=nev,
        which=:LM,
        tol=tol,
        maxiter=maxiter,
        ncv=min(ncv, n - 1),
        ritzvec=true,
        v0=local_v0,
    )
    solve_time = time() - t_solve

    μ = ComplexF64.(μ)
    tiny = abs.(μ) .< 1e-14
    μ[tiny] .= 1e-14
    λ = sigma .+ 1.0 ./ μ
    λs, Xs = sort_by_largest_real(λ, ComplexF64.(X))
    return λs, Xs, nconv, niter, nmult, resid, solve_time
end

function zr_style_python_arpack(
    A,
    B;
    nev::Int=10,
    tol::Float64=1e-10,
    seed::Int=0,
    num_runs::Int=ZR_NUM_EIG_RUNS,
    imag_min::Float64=ZR_IMAG_SHIFT_MIN,
    imag_max::Float64=ZR_IMAG_SHIFT_MAX,
    eigs_per_run::Int=ZR_EIGS_PER_RUN,
)
    n = size(A, 1)
    rng = MersenneTwister(seed)
    v0 = randn(rng, n)
    ncv = min(max(2 * max(nev, 8) + 10, 60), n - 1)

    function run_shift_once(sig, k)
        λ, X, _, _, _, _ = run_shift(A, B; nev=k, sigma=sig, tol=tol, maxiter=5000, ncv=ncv, v0=v0)
        return λ, X
    end

    pool = Tuple{ComplexF64,Vector{ComplexF64},Float64}[]

    function add_pool!(λs, Xs; rr_cut::Float64=1e-6)
        for j in eachindex(λs)
            rr = rel_residual(A, B, λs[j], Xs[:, j])
            if rr > rr_cut
                continue
            end

            merged = false
            for i in eachindex(pool)
                λ0, x0, rr0 = pool[i]
                if same_eig(ComplexF64(λs[j]), λ0)
                    if is_better_candidate(ComplexF64(λs[j]), rr, λ0, rr0)
                        pool[i] = (ComplexF64(λs[j]), ComplexF64.(Xs[:, j]), rr)
                    end
                    merged = true
                    break
                end
            end

            if !merged
                push!(pool, (ComplexF64(λs[j]), ComplexF64.(Xs[:, j]), rr))
            end
        end

        pool = dedup_pool(pool)
        return nothing
    end

    k_run = Int(max(2, min(n - 2, eigs_per_run)))
    n_runs = Int(max(1, num_runs))
    imag_lo = float(min(imag_min, imag_max))
    imag_hi = float(max(imag_min, imag_max))
    imag_grid = collect(range(imag_lo, imag_hi; length=n_runs))

    used_shifts = ComplexF64[]
    for wi in imag_grid
        s = ComplexF64(0.0, wi)
        push!(used_shifts, s)
        try
            λs, Xs = run_shift_once(s, k_run)
            add_pool!(λs, Xs)
        catch
            continue
        end
    end

    pool = dedup_pool(pool)
    if isempty(pool)
        error("ZR style produced no candidates after filtering")
    end

    # Impose conjugate symmetry for real-valued matrices
    sym_pool = copy(pool)
    for (λ, x, rr) in pool
        if abs(imag(λ)) <= 1e-12
            continue
        end
        λc = conj(λ)
        has_conj = any(same_eig(λc, λ0) for (λ0, _, _) in sym_pool)
        if !has_conj
            push!(sym_pool, (ComplexF64(λc), conj.(x), rr))
        end
    end

    pool = dedup_pool(sym_pool)
    p = sortperm(collect(eachindex(pool)); by=i -> (abs(real(pool[i][1])), pool[i][3], abs(imag(pool[i][1]))))

    out_idx = p[1:min(nev, length(p))]
    out = pool[out_idx]

    λ = ComplexF64[t[1] for t in out]
    X = hcat([t[2] for t in out]...)
    rr = Float64[t[3] for t in out]
    meta = (runs=length(used_shifts), imag_min=imag_lo, imag_max=imag_hi, pool_size=length(pool))
    return λ, X, rr, meta
end

function lm_reference(A, B; nev::Int=100, sigma=10.0, tol::Float64=1e-10)
    n = size(A, 1)
    v0 = randn(MersenneTwister(1), n)
    λ, X, nconv, niter, nmult, _, solve_time = run_shift(A, B; nev=max(nev, 12), sigma=sigma, tol=tol, maxiter=1500, ncv=max(nev + 30, 120), v0=v0)
    λ, X = sort_by_largest_real(λ, X)
    meta = (eigsolve_time_s=solve_time, nconv=nconv, niter=niter, nmult=nmult)
    return λ, X, meta
end
 

function main()
    benchmark_lm_only = false
    cli_positional = String[]
    for a in ARGS
        if a == "--benchmark-lm-only"
            benchmark_lm_only = true
        else
            push!(cli_positional, a)
        end
    end

    K = load_sparse_csv("K.csv")
    M = load_sparse_csv("M.csv")

    A = ComplexF64.(-K)
    B = ComplexF64.(M)

    nev = length(cli_positional) >= 1 ? max(1, parse(Int, cli_positional[1])) : REQUESTED_EIGENVALUES
    shift = length(cli_positional) >= 2 ? parse_shift_arg(cli_positional[2]) : ComplexF64(TARGET_SHIFT)

    t1 = time()
    λ_lm, X_lm, lm_meta = lm_reference(A, B; nev=nev, sigma=shift, tol=SOLVER_TOL)
    tlm = time() - t1

    if benchmark_lm_only
        println("LM_EIGENSOLVE_COST_S=", @sprintf("%.9f", lm_meta.eigsolve_time_s))
        println("LM_BENCHMARK_TOTAL_S=", @sprintf("%.9f", tlm))
        println("LM_META nconv=", lm_meta.nconv, " niter=", lm_meta.niter, " nmult=", lm_meta.nmult)
        println("completed")
        return
    end

    t0 = time()
    λ_zr, X_zr, rr_zr, zr_meta = zr_style_python_arpack(
        A,
        B;
        nev=nev,
        tol=SOLVER_TOL,
        seed=RANDOM_SEED,
        num_runs=ZR_NUM_EIG_RUNS,
        imag_min=ZR_IMAG_SHIFT_MIN,
        imag_max=ZR_IMAG_SHIFT_MAX,
        eigs_per_run=ZR_EIGS_PER_RUN,
    )
    tzr = time() - t0

    p1 = scatter(real.(λ_lm), imag.(λ_lm), marker_z=real.(λ_lm), ms=6, alpha=0.85,
                 xlabel="Real(λ)", ylabel="Imag(λ)",
                 title="Julia ARPACK LM (sorted by largest Re)",
                 legend=false, colorbar_title="Real(λ)", grid=true)
    vline!(p1, [0.0], color=:black, lw=1)
    hline!(p1, [0.0], color=:black, lw=1)
    savefig(p1, LM_PLOT_FILE)

    p2 = scatter(real.(λ_zr), imag.(λ_zr), marker_z=real.(λ_zr), ms=6, alpha=0.85,
                 xlabel="Real(λ)", ylabel="Imag(λ)",
                 title="Julia ARPACK ZR style, count=$(length(λ_zr))",
                 legend=false, colorbar_title="Real(λ)", grid=true)
    vline!(p2, [0.0], color=:black, lw=1)
    hline!(p2, [0.0], color=:black, lw=1)
    savefig(p2, ZR_PLOT_FILE)

    

    println(λ_zr)
    println("Julia benchmark | shift: ", shift)
    println("Julia benchmark | ZR elapsed: ", round(tzr, digits=3), " s | count: ", length(λ_zr),
            " | runs: ", zr_meta.runs, " | imag_min: ", zr_meta.imag_min,
            " | imag_max: ", zr_meta.imag_max, " | pool_size: ", zr_meta.pool_size,
            " | rr[min,max]=(", @sprintf("%.2e", minimum(rr_zr)), ",", @sprintf("%.2e", maximum(rr_zr)), ")")
        println("Julia benchmark | LM elapsed: ", round(tlm, digits=3), " s | count: ", length(λ_lm))
    println("completed")
end

main()
