# Generate the static manifold used on website/documentation.html.
#
# Run from the MORFE.jl repository root:
#   julia website/generate_manifold_accent.jl
#
# The output is website/assets/manifold-accent.svg. Edit only the clearly marked
# geometry block below; the remainder turns the sampled surface into smooth SVG
# parameter lines.

using Printf

const SVG_WIDTH = 720
const SVG_HEIGHT = 980
const SVG_PADDING = 36
const OUTPUT_PATH = joinpath(@__DIR__, "assets", "manifold-accent.svg")

# ── EDIT THE MANIFOLD HERE ───────────────────────────────────────────────────

const U_SAMPLES = 19  # number of points along each u-curve
const V_SAMPLES = 13  # number of points along each v-curve

"""Map parameters `(u, v) ∈ [0,1]²` to a surface point `(x, y, z)`."""
function surface(u, v)
    x = 3u - 1
    y = 2.5v - 1

    # Replace this expression with the manifold equation you want to display.
    z = 0.34 * sinpi(0.85x + 0.18) * cospi(0.55y - 1.10) +
        0.12 * sinpi(0.90y + 0.20) +
        0.05 * x * y

    return x, y, z
end

"""Project a surface point into the 720×980 SVG canvas."""
function project(x, y, z)
    # These constants control position, viewing angle and apparent size.
    X = 360 + 255x + 58y + 22z
    Y = 490 + 375y - 288z
    return X, Y
end

# ── END EDITABLE GEOMETRY ────────────────────────────────────────────────────

const Point2 = NTuple{2, Float64}

function smooth_path(points::Vector{Point2})
    length(points) >= 2 || error("A parameter line needs at least two samples")
    io = IOBuffer()
    @printf(io, "M%.1f %.1f", points[1]...)
    for i in 1:(length(points) - 1)
        p0 = points[max(i - 1, 1)]
        p1 = points[i]
        p2 = points[i + 1]
        p3 = points[min(i + 2, length(points))]
        c1 = (p1[1] + (p2[1] - p0[1]) / 6, p1[2] + (p2[2] - p0[2]) / 6)
        c2 = (p2[1] - (p3[1] - p1[1]) / 6, p2[2] - (p3[2] - p1[2]) / 6)
        @printf(io, "C%.1f %.1f %.1f %.1f %.1f %.1f", c1..., c2..., p2...)
    end
    return String(take!(io))
end

function sampled_surface()
    points = Matrix{Point2}(undef, U_SAMPLES, V_SAMPLES)
    for j in 1:V_SAMPLES, i in 1:U_SAMPLES

        u = (i - 1) / (U_SAMPLES - 1)
        v = (j - 1) / (V_SAMPLES - 1)
        points[i, j] = project(surface(u, v)...)
    end
    return points
end

"""Fit projected points inside the SVG without changing their aspect ratio."""
function fit_to_canvas(points::Matrix{Point2})
    xs = first.(points)
    ys = last.(points)
    min_x, max_x = extrema(xs)
    min_y, max_y = extrema(ys)
    span_x = max_x - min_x
    span_y = max_y - min_y
    span_x > 0 && span_y > 0 ||
        error("The projected manifold must span both canvas directions")
    scale = min(
        (SVG_WIDTH - 2SVG_PADDING) / span_x,
        (SVG_HEIGHT - 2SVG_PADDING) / span_y
    )
    offset_x = (SVG_WIDTH - scale * span_x) / 2
    offset_y = (SVG_HEIGHT - scale * span_y) / 2
    return map(points) do point
        (offset_x + scale * (point[1] - min_x), offset_y + scale * (point[2] - min_y))
    end
end

function write_svg(path = OUTPUT_PATH)
    points = fit_to_canvas(sampled_surface())
    xs = first.(points)
    ys = last.(points)
    open(path, "w") do io
        println(io,
            """<svg xmlns="http://www.w3.org/2000/svg" width="$SVG_WIDTH" height="$SVG_HEIGHT" viewBox="0 0 $SVG_WIDTH $SVG_HEIGHT" fill="none">""")
        println(io, "  <!-- Generated by website/generate_manifold_accent.jl. -->")
        println(io, "  <g stroke=\"#9558b2\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\">")
        println(io, "    <g stroke-opacity=\".46\" stroke-width=\"1.15\">")
        for j in axes(points, 2)
            println(io, "      <path d=\"$(smooth_path(collect(points[:, j])))\"/>")
        end
        println(io, "    </g>")
        println(io, "    <g stroke-opacity=\".31\" stroke-width=\".9\">")
        for i in axes(points, 1)
            println(io, "      <path d=\"$(smooth_path(collect(points[i, :])))\"/>")
        end
        println(io, "    </g>")
        println(io, "  </g>")
        println(io, "</svg>")
    end
    @info "Written $path" x_span=extrema(xs) y_span=extrema(ys)
end

write_svg()
